// packages/ui/src/components/NewTaskForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useMutation, useQueryClient } from '@tanstack/vue-query';
import { api } from '../lib/api';

const open = ref(false);
const title = ref('');
const description = ref('');
const queryClient = useQueryClient();

const mutation = useMutation({
  mutationFn: () => api.createTask({ title: title.value, description: description.value || undefined }),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['tasks'] });
    title.value = '';
    description.value = '';
    open.value = false;
  },
});

function submit() {
  if (title.value.trim()) mutation.mutate();
}
</script>

<template>
  <button v-if="!open" type="button" class="add-btn" @click="open = true">+ Nova tarefa</button>
  <form v-else class="form" @submit.prevent="submit">
    <input v-model="title" class="input" placeholder="Título da tarefa" autofocus />
    <textarea
      v-model="description"
      class="input area"
      placeholder="Descrição (opcional)"
    />
    <div class="actions">
      <button type="button" class="cancel" @click="open = false">Cancelar</button>
      <button type="submit" class="submit" :disabled="!title.trim() || mutation.isPending.value">
        {{ mutation.isPending.value ? 'Criando...' : 'Criar' }}
      </button>
    </div>
  </form>
</template>

<style scoped>
.add-btn {
  padding: 10px 16px;
  background: var(--surface);
  border: 1px dashed var(--border);
  border-radius: var(--radius);
  color: var(--text-muted);
  font-size: 14px;
  width: 100%;
}
.form {
  padding: 16px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  display: flex;
  flex-direction: column;
  gap: 10px;
  animation: fadeIn 0.35s var(--ease-out);
}
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
.input {
  padding: 10px 12px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  font-size: 14px;
  outline: none;
}
.area {
  min-height: 60px;
  resize: vertical;
}
.actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
}
.cancel {
  padding: 8px 14px;
  font-size: 13px;
  color: var(--text-muted);
}
.submit {
  padding: 8px 16px;
  background: var(--accent-dim);
  color: var(--bg);
  border-radius: var(--radius);
  font-size: 13px;
  font-weight: 600;
}
.submit:disabled {
  opacity: 0.5;
}
</style>

// packages/ui/src/components/new-task-form.tsx
import { useState } from 'react';
import { motion } from 'motion/react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../lib/api';

export function NewTaskForm() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: () => api.createTask({ title, description: description || undefined }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
      setTitle('');
      setDescription('');
      setOpen(false);
    },
  });

  if (!open) {
    return (
      <motion.button
        onClick={() => setOpen(true)}
        style={styles.addBtn}
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        transition={{ type: 'spring', duration: 0.18, bounce: 0 }}
      >
        + Nova tarefa
      </motion.button>
    );
  }

  return (
    <motion.form
      initial={{ opacity: 0, y: 8, filter: 'blur(4px)' }}
      animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
      exit={{ opacity: 0, y: -12, filter: 'blur(4px)' }}
      transition={{ type: 'spring', duration: 0.45, bounce: 0 }}
      style={styles.form}
      onSubmit={(e) => {
        e.preventDefault();
        if (title.trim()) mutation.mutate();
      }}
    >
      <input
        placeholder="Título da tarefa"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        style={styles.input}
        autoFocus
      />
      <textarea
        placeholder="Descrição (opcional)"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        style={{ ...styles.input, minHeight: 60, resize: 'vertical' }}
      />
      <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
        <button type="button" onClick={() => setOpen(false)} style={styles.cancelBtn}>
          Cancelar
        </button>
        <motion.button
          type="submit"
          disabled={!title.trim() || mutation.isPending}
          style={styles.submitBtn}
          whileTap={{ scale: 0.97 }}
        >
          {mutation.isPending ? 'Criando...' : 'Criar'}
        </motion.button>
      </div>
    </motion.form>
  );
}

const styles: Record<string, React.CSSProperties> = {
  addBtn: {
    padding: '10px 16px',
    background: 'var(--surface)',
    border: '1px dashed var(--border)',
    borderRadius: 'var(--radius)',
    color: 'var(--text-muted)',
    fontSize: 14,
    width: '100%',
  },
  form: {
    padding: 16,
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  input: {
    padding: '10px 12px',
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontSize: 14,
    outline: 'none',
  },
  cancelBtn: {
    padding: '8px 14px',
    fontSize: 13,
    color: 'var(--text-muted)',
  },
  submitBtn: {
    padding: '8px 16px',
    background: 'var(--accent-dim)',
    color: 'var(--bg)',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 600,
  },
};
