// packages/ui/src/components/status-bar.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../lib/api';
import { StatusSkeleton } from './skeleton';

export function StatusBar() {
  const queryClient = useQueryClient();

  const { data: health, isLoading } = useQuery({
    queryKey: ['health'],
    queryFn: api.health,
  });

  const startMutation = useMutation({
    mutationFn: api.startAgent,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['health'] });
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
  });

  const stopMutation = useMutation({
    mutationFn: api.stopAgent,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['health'] }),
  });

  if (isLoading) return <StatusSkeleton />;

  const agentRunning = health?.agent.running ?? false;

  return (
    <div style={styles.bar}>
      <Indicator label="LLM" active={health?.llm ?? false} />
      <Indicator label="Agente" active={agentRunning} />
      <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
        {agentRunning ? (
          <button
            onClick={() => stopMutation.mutate()}
            disabled={stopMutation.isPending}
            style={{ ...styles.btn, ...styles.btnDanger }}
          >
            Parar agente
          </button>
        ) : (
          <button
            onClick={() => startMutation.mutate()}
            disabled={startMutation.isPending}
            style={{ ...styles.btn, ...styles.btnPrimary }}
          >
            Iniciar agente
          </button>
        )}
      </div>
    </div>
  );
}

function Indicator({ label, active }: { label: string; active: boolean }) {
  return (
    <div style={styles.indicator}>
      <span style={{ ...styles.dot, background: active ? 'var(--success)' : 'var(--danger)' }} />
      <span style={{ color: 'var(--text-muted)', fontSize: 13 }}>{label}</span>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{active ? 'online' : 'offline'}</span>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  bar: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: '12px 20px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg)',
  },
  indicator: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
  },
  btn: {
    padding: '7px 14px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 600,
  },
  btnPrimary: {
    background: 'var(--accent-dim)',
    color: 'var(--bg)',
  },
  btnDanger: {
    background: 'transparent',
    color: 'var(--danger)',
    border: '1px solid var(--danger)',
  },
};

// packages/ui/src/components/StatusBar.vue
<script setup lang="ts">
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import { api } from '../lib/api';
import StatusSkeleton from './skeleton/StatusSkeleton.vue';

const queryClient = useQueryClient();

const { data: health, isLoading } = useQuery({
  queryKey: ['health'],
  queryFn: api.health,
});

const { data: whatsapp } = useQuery({
  queryKey: ['whatsapp'],
  queryFn: api.whatsappStatus,
  refetchInterval: 15000,
  retry: false,
});

const startMutation = useMutation({
  mutationFn: api.startAgent,
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['health'] });
    queryClient.invalidateQueries({ queryKey: ['tasks'] });
  },
});

const stopMutation = useMutation({
  mutationFn: api.stopAgent,
  onSuccess: () => queryClient.invalidateQueries({ queryKey: ['health'] }),
});
</script>

<template>
  <StatusSkeleton v-if="isLoading" />
  <div v-else class="bar">
    <div class="indicator">
      <span
        class="dot"
        :style="{ background: health?.llm ? 'var(--success)' : 'var(--danger)' }"
      />
      <span class="label">LLM</span>
      <span class="state">{{ health?.llm ? 'online' : 'offline' }}</span>
    </div>
    <div class="indicator">
      <span
        class="dot"
        :style="{
          background: health?.agent.running ? 'var(--success)' : 'var(--danger)',
        }"
      />
      <span class="label">Agente</span>
      <span class="state">{{ health?.agent.running ? 'online' : 'offline' }}</span>
    </div>
    <div class="indicator">
      <span
        class="dot"
        :style="{
          background:
            whatsapp?.config.enabled &&
            whatsapp.sessions?.some((s) => s.connection.connected)
              ? 'var(--success)'
              : 'var(--danger)',
        }"
      />
      <span class="label">WhatsApp</span>
      <span class="state">
        {{
          whatsapp?.config.enabled &&
          whatsapp.sessions?.some((s) => s.connection.connected)
            ? 'online'
            : 'offline'
        }}
      </span>
    </div>
    <div class="actions">
      <button
        v-if="health?.agent.running"
        type="button"
        class="btn btn-danger"
        :disabled="stopMutation.isPending.value"
        @click="stopMutation.mutate()"
      >
        Parar agente
      </button>
      <button
        v-else
        type="button"
        class="btn btn-primary"
        :disabled="startMutation.isPending.value"
        @click="startMutation.mutate()"
      >
        Iniciar agente
      </button>
    </div>
  </div>
</template>

<style scoped>
.bar {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 12px 20px;
  border-bottom: 1px solid var(--border);
  background: var(--bg);
}
.indicator {
  display: flex;
  align-items: center;
  gap: 8px;
}
.dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
}
.label {
  color: var(--text-muted);
  font-size: 13px;
}
.state {
  font-family: var(--font-mono);
  font-size: 12px;
}
.actions {
  margin-left: auto;
  display: flex;
  gap: 8px;
}
.btn {
  padding: 7px 14px;
  border-radius: var(--radius);
  font-size: 13px;
  font-weight: 600;
}
.btn-primary {
  background: var(--accent-dim);
  color: var(--bg);
}
.btn-danger {
  background: transparent;
  color: var(--danger);
  border: 1px solid var(--danger);
}
</style>
